# Generated by Django 5.0.4 on 2024-04-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeederStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_manual_mode', models.BooleanField(default=False)),
                ('food_level_low', models.BooleanField(default=False)),
            ],
        ),
    ]
