# Generated by Django 5.0.4 on 2024-05-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feederstatus',
            name='dispense',
            field=models.BooleanField(default=False),
        ),
    ]
